name: "@ Call - EasyPark UITests Workflow"

on:
  workflow_call:
    inputs:
      runs-on-json:
        description: 'Override "runs-on"'
        required: false
        default: '["self-hosted","macOS","ARM64","xcode-15"]'
        type: string

jobs:
  tests:
    name: "Tests"
    environment: app1/prod
    timeout-minutes: 20
    runs-on: ${{ fromJson(inputs.runs-on-json) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Run Tests
        run: |
          echo "⏳ Running tests"
          echo "Runs on: ${{ toJson(fromJson(inputs.runs-on-json)) }}"
          echo "✅ Done"
