name: "App 1 Unit Tests Workflow"

on:
  workflow_call:
    inputs:
      runs-on-json:
        description: 'Override "runs-on"'
        type: string
        required: false
        default: '["macos-latest"]'
      files-changed:
        description: 'Files changed'
        type: boolean
        required: false
        default: true

jobs:
  tests:
    name: "Tests"
    environment: app1/prod
    timeout-minutes: 20
    runs-on: ${{ fromJson(inputs.runs-on-json) }}

    steps:
      - name: Checkout
        if: ${{ inputs.files-changed == true }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Run Tests
        if: ${{ inputs.files-changed == true }}
        run: |
          echo "⏳ Running tests"
          echo "Runs on: ${{ toJson(fromJson(inputs.runs-on-json)) }}"
          echo "✅ Done"
