name: "# PR"

on:
  workflow_dispatch:
  merge_group:
  pull_request:

concurrency:
  group: pr-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-avoidance:
    name: Changed Files (Build Avoidance)
    timeout-minutes: 10
    outputs:
      app1: ${{ steps.app-1-changed.outputs.any_changed }}
    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if App1 code has changed
        id: app-1-changed
        uses: tj-actions/changed-files@v42
        with:
          files: |
            Apps/App1/
          files_ignore: |
            **/*.md
            utils/lint-rules/

  app1-test:
    # Required checks need to run but not necessarily do anything
    needs: build-avoidance
    # name: App1/Unit Tests
    uses: ./.github/workflows/app1-unit-test.yaml
    secrets: inherit
